#!/usr/bin/env bash

iptables -F # Flush
iptables -t nat -A POSTROUTING -s $VPNIPPOOL -o eth0 -m policy --pol ipsec --dir out -j ACCEPT
iptables -t nat -A POSTROUTING -s $VPNIPPOOL -o eth0 -j MASQUERADE

# Store iptable rules so iptables-persistent can bring them back up on reboot
iptables-save > /etc/iptables/rules.v4
