#!/usr/bin/env bash
# TODO: Ownership of /etc/ipsec.secrets?
# TODO: Don't use Google VPN - is there a better alternative?
# TODO: Close root SSH access and add another user

export VPNIPPOOL="10.20.30.0/24"

# Required packages
apt-get update # This has already been done by Fodor, but it's not liking it for some reason
apt-get -y install strongswan strongswan-plugin-openssl strongswan-plugin-eap-mschapv2 iptables-persistent unattended-upgrades

# StrongSwan
rm /etc/strongswan.conf
cp "${INSTALLPATH}/configs/strongswan.conf" /etc/strongswan.conf

# IPSec - has replacements so can't symlink it
rm /etc/ipsec.conf
cat > /etc/ipsec.conf <<EOF
config setup
  uniqueids=no
  charondebug=dmn -1, mgr -1, ike -1, chd -1, job -1, cfg -1, knl -1, net -1, asn -1, enc -1, lib -1, esp -1, tls -1, tnc -1, imc -1, imv -1, pts -1

conn %default
 mobike=yes
 dpdaction=clear
 dpddelay=35s
 dpdtimeout=200s
 fragmentation=yes

conn IKEV2
  auto=add
  compress=no
  type=tunnel
  keyexchange=ikev2
  fragmentation=yes
  forceencaps=yes
  ike=aes256-sha1-modp1024,3des-sha1-modp1024!
  esp=aes256-sha1,3des-sha1!
  dpdaction=clear
  dpddelay=200s
  rekey=no
  left=%any
  leftid=@${DOMAIN}
  leftauth=psk
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  right=%any
  rightid=%any
  rightauth=eap-mschapv2
  eap_identity=%any
  rightdns=8.8.8.8,8.8.4.4
  rightsubnet=${VPNIPPOOL}
  rightsourceip=${VPNIPPOOL}
  rightsendcert=never
EOF

sed -i -e 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
service ssh restart

# Required VPN changes
echo '
net.ipv4.ip_forward = 1
net.ipv4.ip_no_pmtu_disc = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
' >> /etc/sysctl.conf

sysctl -p

# Persistent IPTables
/usr/bin/env bash "${INSTALLPATH}/provisioning/iptables"

# VPN Users & Passwords
rm /etc/ipsec.secrets

echo "${DOMAIN} : PSK \"${VPNSECRET}\"" > /etc/ipsec.secrets
/usr/bin/env bash ${INSTALLPATH}/bin/adduser "${VPNUSERNAME}" "${VPNPASSWORD}"

# Disable apparmor for charon
ln -s /etc/apparmor.d/usr.lib.ipsec.charon /etc/apparmor.d/disable/
apparmor_parser -R /etc/apparmor.d/usr.lib.ipsec.charon

ipsec restart

# Unattended upgrades
/usr/bin/env bash ${INSTALLPATH}/provisioning/unattended-upgrades
